project_token: d96473e6ba0bb61f82cf397c
name: TuriTextClassifier
jobs:
  - job_id: d6e8617f-029f-4b41-b6d5-cbbdc751f4ae
    language: python
    name: sentiment_classifier
    entrypoint: "sentiment_classifier.ipynb"